### ISSUE TITLE
No PSK available. Unable to resume

### ISSUE THREAD

**Issue by cxbrooks** [icyphy/kepler-build#1]
While running build-kepler.sh under openjdk11 in Travis, the following message appears:

> [change-to] Downloaded from nativelibs4java-repo: http://nativelibs4java.sourceforge.net/maven/com/nativelibs4java/bridj/0.6/bridj-0.6-c-only.jar (738 kB at 196 kB/s)
> [change-to] [INFO] ------------------------------------------------------------------------
> [change-to] [INFO] BUILD FAILURE
> [change-to] [INFO] ------------------------------------------------------------------------
> [change-to] [INFO] Total time:  04:10 min
> [change-to] [INFO] Finished at: 2021-11-06T02:09:40Z
> [change-to] [INFO] ------------------------------------------------------------------------
> [change-to] [ERROR] Failed to execute goal on project kepler-gis: Could not resolve dependencies for project org.kepler-project:kepler-gis:jar:0.1.0: The following artifacts could not be resolved: org.geotools:gt-shapefile:jar:19.0, org.geotools:gt-data:jar:19.0, javax.media:jai_core:jar:1.1.3, org.geotools:gt-referencing:jar:19.0: Could not transfer artifact org.geotools:gt-shapefile:jar:19.0 from/to boundless (https://repo.osgeo.org/repository/release/): Transfer failed for https://repo.osgeo.org/repository/release/org/geotools/gt-shapefile/19.0/gt-shapefile-19.0.jar: No PSK available. Unable to resume. -> [Help 1]

The message "No PSK available. Unable to resume" is key

* [javax.net.ssl.SSLException: No PSK available. Unable to resume](https://stackoverflow.com/questions/52574050/javax-net-ssl-sslexception-no-psk-available-unable-to-resume) (stackoverflow) suggests a compile-time flag or editing a properties file.

**Comment by cxbrooks** [comment]
Under MacOS 10.14.6, with

```
bash-3.2$ mvn -v
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T11:41:47-07:00)
Maven home: /usr/local/apache-maven
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/openjdk/jdk-11.0.2.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
bash-3.2$ java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
bash-3.2$
```

after removing ~/.m2, build-kepler.sh errored with:

> [change-to] [ERROR] Failed to execute goal on project kepler-gis: Could not resolve dependencies for project org.kepler-project:kepler-gis:jar:0.1.0: The following artifacts could not be resolved: it.geosolutions.jaiext.algebra:jt-algebra:jar:1.0.20, it.geosolutions.jaiext.bandcombine:jt-bandcombine:jar:1.0.20, org.geotools:gt-grid:jar:19.0, org.geotools:gt-wfs-ng:jar:19.0: Could not transfer artifact it.geosolutions.jaiext.algebra:jt-algebra:jar:1.0.20 from/to maven2-repository.dev.java.net (http://download.java.net/maven/2): peer not authenticated -> [Help 1]

However, removing ~/.m2 and running
```
cd kepler-build/gis/module-info
mvn dependency:copy-dependencies
```
did not trigger either error.

**Comment by cxbrooks** [comment]
This seems to be fixed by updating ${JAVA_HOME}/conf/security/java.security to include `TLSv1.3`.  

Sadly, I could not figure out how to install a more recent version of OpenJDK 11.x into Travis that might have this bug fixed.

```
matrix:
  include:
    - env: JDK='Oracle JDK 9'
      jdk: oraclejdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - env: JDK='Oracle OpenJDK 10'
      jdk: openjdk10
    - env: JDK='Oracle OpenJDK 11'
      jdk: openjdk11
      before_install:
        # Fix "No PSK available. Unable to resume" in jdk 11.0.2
        # See https://github.com/icyphy/kepler-build/issues/1
        # and https://stackoverflow.com/questions/52574050/javax-net-ssl-sslexception-no-psk-available-unable-to-resume
        # Figuring out how to upgrade to jdk 11.0.3 or later might also work.
        - ant -version
	- echo ${JAVA_HOME}
        - ls ${JAVA_HOME}
        - ls ${JAVA_HOME}/conf
        - ls ${JAVA_HOME}/conf/security
        - ls -l ${JAVA_HOME}/conf/security/java.security
        - cat ${JAVA_HOME}/conf/security/java.security
        - sed 's/jdk.tls.disabledAlgorithms=/jdk.tls.disabledAlgorithms=TLSv1.3, /' ${JAVA_HOME}/conf/security/java.security > /tmp/java.security.new
	- diff /tmp/java.security.new ${JAVA_HOME}/conf/security/java.security || true
        - sudo mv /tmp/java.security.new ${JAVA_HOME}/conf/security/java.security
        - ls -l ${JAVA_HOME}/conf/security/java.security
        - grep jdk.tls.disabledAlgorithms= ${JAVA_HOME}/conf/security/java.security || true
    - env: JDK='Oracle OpenJDK 12'
      jdk: openjdk12
```
